apiVersion: v1
kind: Namespace
metadata:
  name: app1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: app1
  labels:
    app: python-app
spec:
  replicas: 0
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app
          image: sudoharish/api-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8005
---
apiVersion: v1
kind: Service
metadata:
  name: python-app-svc
  namespace: app1
  labels:
    app: python-app
spec:
  type: ClusterIP
  selector:
    app: python-app
  ports:
    - port: 8005
      targetPort: 8005
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: python-app-ingress
  namespace: app1
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: do.himalyan.top
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: python-app-svc
            port:
              number: 8005
