name: Deploy to Kind

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment (e.g. ENV_dev7)"
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
          ls -la

      - name: Verify cluster access
        run: kubectl cluster-info

      - name: Apply manifests
        run: kubectl apply -f my-public-ip.yml
